spring.datasource.url=jdbc:mysql://localhost:3306/system_user_db?createDatabaseIfNotExist=true&serverTimeZone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=gabriel
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

system.user.security.token.secret-key=${SYSTEM_USER_JWT_SECRET_KEY:7f4c9b1a8e2d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b}